version: 2

models:
  - name: stg_listings
    description: Model of AirBnB listings in Colorado
    columns:
      - name: listing_id
        description: primary key
        tests:
          - not_null
          - unique
